1. Convert List to 1D Array

In [3]:
import numpy as np

In [5]:
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
# Expected Output:
# Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]
List = [12.23, 13.32, 100, 36.32]
arr = np.array(List)
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create 3x3 Matrix (2?10)

In [11]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
# Expected Output:
# [[ 2 3 4] [ 5 6 7] [ 8 9 10]]
arr = np.arange(2,11,1)
arr1 = arr.reshape(3,3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Null Vector (10) & Update Sixth Value

In [14]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]
vector = np.zeros(10)
vector[5] = 11
print(vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Array from 12 to 38

In [16]:
# Write a NumPy program to create an array with values ranging from 12 to 38.
# Expected Output:
# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
array = np.arange(12,38)
print(array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


5. Convert Array to Float Type

In [20]:
# Write a NumPy program to convert an array to a floating type.
# Sample output:
# Original array [1, 2, 3, 4]
array = np.arange(1,5)
float = array.astype(float)
print(float)

[1. 2. 3. 4.]


6. Celsius to Fahrenheit Conversion

In [21]:
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
# Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
# Expected Output:
# Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]
# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]
centigrade = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
fahrenheit = centigrade * 9 / 5 + 32
print(centigrade)
print(fahrenheit)

[-17.78 -11.11   7.34   1.11  37.73   0.  ]
[-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


7. Append Values to Array (Do self-tudy)

In [23]:
# Write a NumPy program to append values to the end of an array.
# Expected Output:
# Original array: [10, 20, 30]
# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
array = np.array([10, 20, 30])
arr = [40,50,60,70,80,90]
array1 = np.append(array, arr)
print(array1)

[10 20 30 40 50 60 70 80 90]


8. Array Statistical Functions (Do self-tudy)

In [42]:
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
array = np.random.randint(1,100,(1,10))
mean = np.mean(array)
median = np.median(array)
STD = np.std(array)
print(mean)
print(median)
print(STD)

53.5
51.5
27.83971982617641


9 Find min and max

In [77]:
# Create a 10x10 array with random values and find the minimum and maximum values.
array = np.random.randint(1,100,(10,10))
min = np.min(array)
max = np.max(array)
print(min)
print(max)

1
98


10 

In [81]:
# Create a 3x3x3 array with random values.
array = np.random.randint(1,100,(3,3,3))
array

array([[[ 7, 19, 67],
        [89, 88,  6],
        [14, 63,  9]],

       [[11, 19, 69],
        [53, 63, 12],
        [56, 62, 28]],

       [[10, 19, 80],
        [93, 85, 35],
        [91, 33, 25]]], dtype=int32)